/**
 * ProjektZespolowy-WSIZ
 * This is ProjektZespolowy-WSIZ API contract
 *
 * OpenAPI spec version: 1.1.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionCategory } from './transactionCategory';


export interface Transaction { 
    id?: string;
    description?: string;
    amount?: number;
    date?: string;
    category?: TransactionCategory;
    type?: Transaction.TypeEnum;
}
export namespace Transaction {
    export type TypeEnum = 'INCOME' | 'EXPENSE';
    export const TypeEnum = {
        INCOME: 'INCOME' as TypeEnum,
        EXPENSE: 'EXPENSE' as TypeEnum
    };
}
