swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  description: "This is ProjektZespolowy-WSIZ API contract"
  version: "1.1.0"
  title: "ProjektZespolowy-WSIZ"
  contact:
    email: "apiteam@swagger.io"

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: "localhost:8080"
basePath: "/"
tags:
  - name: "User"
    description: "Operations related to users"
  - name: "Expense"
    description: "Operations related to expenses"
  - name: "Income"
    description: "Operations related to incomes"
  - name: "Category"
    description: "Operations related to categories"

schemes:
  - "http"

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /users:
    get:
      tags:
        - "User"
      summary: "Get all users"
      operationId: getUsers
      description: "Retrieve a list of all users"
      responses:
        200:
          description: "A list of users"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
    post:
      tags:
        - "User"
      summary: "Create a new user"
      operationId: createUser
      description: "Create a new user"
      parameters:
        - in: "body"
          name: "body"
          description: "User object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "User created"
          schema:
            $ref: "#/definitions/User"

  /users/{id}:
    get:
      tags:
        - "User"
      summary: "Get a user by ID"
      operationId: getUser
      description: "Retrieve a user by their ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        200:
          description: "A single user"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
    put:
      tags:
        - "User"
      summary: "Update a user by ID"
      operationId: updateUser
      description: "Update a user by their ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "Updated user object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: "User updated"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
    delete:
      tags:
        - "User"
      summary: "Delete a user by ID"
      operationId: deleteUser
      description: "Delete a user by their ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        204:
          description: "User deleted"
        404:
          description: "User not found"

  /transactions:
    get:
      tags:
        - "Transaction"
      summary: "Get all transactions"
      operationId: getTransactions
      description: "Retrieve a list of all transactions"
      responses:
        200:
          description: "A list of transactions"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Transaction"
    post:
      tags:
        - "Transaction"
      summary: "Create a new transaction"
      operationId: createTransaction
      description: "Create a new transaction"
      parameters:
        - in: "body"
          name: "body"
          description: "Transaction object"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        201:
          description: "Transaction created"
          schema:
            $ref: "#/definitions/Transaction"

  /transactions/{id}:
    get:
      tags:
        - "Transaction"
      summary: "Get a transaction by ID"
      operationId: getTransaction
      description: "Retrieve a transaction by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        200:
          description: "A single transaction"
          schema:
            $ref: "#/definitions/Transaction"
        404:
          description: "Transaction not found"
    put:
      tags:
        - "Transaction"
      summary: "Update a transaction by ID"
      operationId: updateTransaction
      description: "Update a transaction by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "Updated transaction object"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        200:
          description: "Transaction updated"
          schema:
            $ref: "#/definitions/Transaction"
        404:
          description: "Transaction not found"
    delete:
      tags:
        - "Transaction"
      summary: "Delete a transaction by ID"
      operationId: deleteTransaction
      description: "Delete a transaction by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        204:
          description: "Transaction deleted"
        404:
          description: "Transaction not found"

  /transaction-categories:
    get:
      tags:
        - "TransactionCategory"
      summary: "Get all transaction categories"
      operationId: getTransactionCategories
      description: "Retrieve a list of all transaction categories"
      responses:
        200:
          description: "A list of transaction categories"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TransactionCategory"
    post:
      tags:
        - "TransactionCategory"
      summary: "Create a new transaction category"
      operationId: createTransactionCategory
      description: "Create a new transaction category"
      parameters:
        - in: "body"
          name: "body"
          description: "Transaction category object"
          required: true
          schema:
            $ref: "#/definitions/TransactionCategory"
      responses:
        201:
          description: "Transaction category created"
          schema:
            $ref: "#/definitions/TransactionCategory"

  /transaction-categories/{id}:
    get:
      tags:
        - "TransactionCategory"
      summary: "Get a transaction category by ID"
      operationId: getTransactionCategory
      description: "Retrieve a transaction category by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        200:
          description: "A single transaction category"
          schema:
            $ref: "#/definitions/TransactionCategory"
        404:
          description: "Transaction category not found"
    put:
      tags:
        - "TransactionCategory"
      summary: "Update a transaction category by ID"
      operationId: updateTransactionCategory
      description: "Update a transaction category by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "Updated transaction category object"
          required: true
          schema:
            $ref: "#/definitions/TransactionCategory"
      responses:
        200:
          description: "Transaction category updated"
          schema:
            $ref: "#/definitions/TransactionCategory"
        404:
          description: "Transaction category not found"
    delete:
      tags:
        - "TransactionCategory"
      summary: "Delete a transaction category by ID"
      operationId: deleteTransactionCategory
      description: "Delete a transaction category by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        204:
          description: "Transaction category deleted"
        404:
          description: "Transaction category not found"

  /reports:
    get:
      tags:
        - "Report"
      summary: "Get all reports"
      operationId: getReports
      description: "Retrieve a list of all reports"
      responses:
        200:
          description: "A list of reports"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Report"
    post:
      tags:
        - "Report"
      summary: "Create a new report"
      operationId: createReport
      description: "Create a new report"
      parameters:
        - in: "body"
          name: "body"
          description: "Report object"
          required: true
          schema:
            $ref: "#/definitions/Report"
      responses:
        201:
          description: "Report created"
          schema:
            $ref: "#/definitions/Report"

  /reports/{id}:
    get:
      tags:
        - "Report"
      summary: "Get a report by ID"
      operationId: getReport
      description: "Retrieve a report by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        200:
          description: "A single report"
          schema:
            $ref: "#/definitions/Report"
        404:
          description: "Report not found"
    put:
      tags:
        - "Report"
      summary: "Update a report by ID"
      operationId: updateReport
      description: "Update a report by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "Updated report object"
          required: true
          schema:
            $ref: "#/definitions/Report"
      responses:
        200:
          description: "Report updated"
          schema:
            $ref: "#/definitions/Report"
        404:
          description: "Report not found"
    delete:
      tags:
        - "Report"
      summary: "Delete a report by ID"
      operationId: deleteReport
      description: "Delete a report by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        204:
          description: "Report deleted"
        404:
          description: "Report not found"

  /forecasts:
    get:
      tags:
        - "Forecast"
      summary: "Get all forecasts"
      operationId: getForecasts
      description: "Retrieve a list of all forecasts"
      responses:
        200:
          description: "A list of forecasts"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Forecast"
    post:
      tags:
        - "Forecast"
      summary: "Create a new forecast"
      operationId: createForecast
      description: "Create a new forecast"
      parameters:
        - in: "body"
          name: "body"
          description: "Forecast object"
          required: true
          schema:
            $ref: "#/definitions/Forecast"
      responses:
        201:
          description: "Forecast created"
          schema:
            $ref: "#/definitions/Forecast"

  /forecasts/{id}:
    get:
      tags:
        - "Forecast"
      summary: "Get a forecast by ID"
      operationId: getForecast
      description: "Retrieve a forecast by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        200:
          description: "A single forecast"
          schema:
            $ref: "#/definitions/Forecast"
        404:
          description: "Forecast not found"
    put:
      tags:
        - "Forecast"
      summary: "Update a forecast by ID"
      operationId: updateForecast
      description: "Update a forecast by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "Updated forecast object"
          required: true
          schema:
            $ref: "#/definitions/Forecast"
      responses:
        200:
          description: "Forecast updated"
          schema:
            $ref: "#/definitions/Forecast"
        404:
          description: "Forecast not found"
    delete:
      tags:
        - "Forecast"
      summary: "Delete a forecast by ID"
      operationId: deleteForecast
      description: "Delete a forecast by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        204:
          description: "Forecast deleted"
        404:
          description: "Forecast not found"

################################################################################
#                                       Definitions                            #
################################################################################
definitions:

  User:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      username:
        type: "string"
      email:
        type: "string"
        format: "email"
      password:
        type: "string"
      transactions:
        type: "array"
        items:
          $ref: "#/definitions/Transaction"
      customCategories:
        type: "array"
        items:
          $ref: "#/definitions/TransactionCategory"

  Transaction:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      description:
        type: "string"
      amount:
        type: "number"
        format: "double"
      date:
        type: "string"
        format: "date"
      category:
        $ref: "#/definitions/TransactionCategory"
      type:
        type: "string"
        enum:
          - "INCOME"
          - "EXPENSE"

  TransactionCategory:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      name:
        type: "string"
      expenseLimit:
        type: "number"
        format: "double"
      type:
        type: "string"
        enum:
          - "INCOME"
          - "EXPENSE"

  Report:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      startDate:
        type: "string"
        format: "date"
      endDate:
        type: "string"
        format: "date"
      type:
        type: "string"

  Forecast:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      forecastDate:
        type: "string"
        format: "date"
      predictedAmount:
        type: "number"
        format: "double"
      type:
        type: "string"

