spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProjektZespolowy-WSIZ
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type: trace
        show-sql: 'true'


security:
  jwt:
    secret-key: itsmysecretkeywithlengthgreaterthan256bitsanditsverysecure
    expiration-time: 3600000

