export * from './forecast.service';
import { ForecastService } from './forecast.service';
export * from './report.service';
import { ReportService } from './report.service';
export * from './transaction.service';
import { TransactionService } from './transaction.service';
export * from './transactionCategory.service';
import { TransactionCategoryService } from './transactionCategory.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [ForecastService, ReportService, TransactionService, TransactionCategoryService, UserService];
