/**
 * ProjektZespolowy-WSIZ
 * This is ProjektZespolowy-WSIZ API contract
 *
 * OpenAPI spec version: 1.1.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { IncomeCategory } from '../model/incomeCategory';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class IncomeCategoryService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a new income category
     * Create a new income category
     * @param incomeCategory Income category object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createIncomeCategory(incomeCategory: IncomeCategory, observe?: 'body', reportProgress?: boolean): Observable<IncomeCategory>;
    public createIncomeCategory(incomeCategory: IncomeCategory, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncomeCategory>>;
    public createIncomeCategory(incomeCategory: IncomeCategory, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncomeCategory>>;
    public createIncomeCategory(incomeCategory: IncomeCategory, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (incomeCategory === null || incomeCategory === undefined) {
            throw new Error('Required parameter incomeCategory was null or undefined when calling createIncomeCategory.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<IncomeCategory>(`${this.configuration.basePath}/income-categories`,
            incomeCategory,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete an income category by ID
     * Delete an income category by its ID
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteIncomeCategory(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteIncomeCategory(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteIncomeCategory(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteIncomeCategory(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteIncomeCategory.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.configuration.basePath}/income-categories/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all income categories
     * Retrieve a list of all income categories
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIncomeCategories(observe?: 'body', reportProgress?: boolean): Observable<Array<IncomeCategory>>;
    public getIncomeCategories(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<IncomeCategory>>>;
    public getIncomeCategories(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<IncomeCategory>>>;
    public getIncomeCategories(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<IncomeCategory>>(`${this.configuration.basePath}/income-categories`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get an income category by ID
     * Retrieve an income category by its ID
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIncomeCategory(id: string, observe?: 'body', reportProgress?: boolean): Observable<IncomeCategory>;
    public getIncomeCategory(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncomeCategory>>;
    public getIncomeCategory(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncomeCategory>>;
    public getIncomeCategory(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getIncomeCategory.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<IncomeCategory>(`${this.configuration.basePath}/income-categories/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update an income category by ID
     * Update an income category by its ID
     * @param id 
     * @param incomeCategory Updated income category object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateIncomeCategory(id: string, incomeCategory: IncomeCategory, observe?: 'body', reportProgress?: boolean): Observable<IncomeCategory>;
    public updateIncomeCategory(id: string, incomeCategory: IncomeCategory, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncomeCategory>>;
    public updateIncomeCategory(id: string, incomeCategory: IncomeCategory, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncomeCategory>>;
    public updateIncomeCategory(id: string, incomeCategory: IncomeCategory, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateIncomeCategory.');
        }
        if (incomeCategory === null || incomeCategory === undefined) {
            throw new Error('Required parameter incomeCategory was null or undefined when calling updateIncomeCategory.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<IncomeCategory>(`${this.configuration.basePath}/income-categories/${encodeURIComponent(String(id))}`,
            incomeCategory,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
